{{ if has .Values.backendType (list "grpc" "http") }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "base-service.fullname" . }}
  labels:
    {{- include "base-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: {{ .Values.backendType }}
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.backendType }}
      protocol: TCP
  selector:
    {{- include "base-service.selectorLabels" . | nindent 4 }}
{{ end }}