apiVersion: v1
kind: Service
metadata:
  name: {{ include "eventstore.fullname" . }}-admin
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/name: {{ include "eventstore.name" . }}
    helm.sh/chart: {{ include "eventstore.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: admin
spec:
  type: {{ .Values.admin.serviceType }}
  selector:
    app.kubernetes.io/name: {{ include "eventstore.name" . }}-admin
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.extHttpPort }}
      targetPort: {{ .Values.extHttpPort }}
